services:
  a4s-api:
    # Force x86_64 for sqlite-vec compatibility on Apple Silicon.
    # Remove if sqlite-vec adds proper ARM64 Linux wheels.
    platform: linux/amd64
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    user: root
    env_file:
      - api/.env
    environment:
      - API_BASE_URL=http://a4s-api:8000
      - AGENT_NETWORK=a4s-network
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - model-cache:/root/.cache
    networks:
      - a4s-network

  qdrant:
    image: qdrant/qdrant:v1.16
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/data
    networks:
      - a4s-network

  falkordb:
    image: falkordb/falkordb:v4.16.0
    ports:
      - "6379:6379"
      - "3000:3000"
    volumes:
      - falkordb-data:/data
    networks:
      - a4s-network

networks:
  a4s-network:
    name: a4s-network

volumes:
  qdrant-data:
  falkordb-data:
  # Model cache for fastembed
  model-cache:
